// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmzjerxwiauxnurbraak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtemplcnh3aWF1eG51cmJyYWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzA5MDksImV4cCI6MjA2MzUwNjkwOX0.4xLmwJLLvCyXaGNrsWuyO6eAyEQaCgud5ZacJjey06w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);